"""add interview and start date fields to proceso

Revision ID: 3c28aa54d171
Revises: 69057232c3d4
Create Date: 2026-02-16 11:39:00.279444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c28aa54d171'
down_revision: Union[str, None] = '69057232c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proceso', sa.Column('CF_interview', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proceso', sa.Column('client_interview', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proceso', sa.Column('offer_interview', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proceso', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proceso', 'start_date')
    op.drop_column('proceso', 'offer_interview')
    op.drop_column('proceso', 'client_interview')
    op.drop_column('proceso', 'CF_interview')
    # ### end Alembic commands ###
