"""initial_tables

Revision ID: 69057232c3d4
Revises: 
Create Date: 2026-02-15 21:12:00.526959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69057232c3d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('linkedin_url', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('residence_area', sa.Enum('BUENOS_AIRES', 'CATAMARCA', 'CHACO', 'CHUBUT', 'CORDOBA', 'CORRIENTES', 'ENTRE_RIOS', 'FORMOSA', 'JUJUY', 'LA_PAMPA', 'LA_RIOJA', 'MENDOZA', 'MISIONES', 'NEUQUEN', 'RIO_NEGRO', 'SALTA', 'SAN_JUAN', 'SAN_LUIS', 'SANTA_CRUZ', 'SANTA_FE', 'SANTIAGO_DEL_ESTERO', 'TIERRA_DEL_FUEGO', 'TUCUMAN', name='provinciaargentina'), nullable=True),
    sa.Column('salary_expectations', sa.Integer(), nullable=True),
    sa.Column('notice_period', sa.Enum('IMMEDIATE', 'ONE_WEEK', 'TWO_WEEKS', 'THREE_WEEKS', 'FOUR_WEEKS', 'MORE_THAN_FOUR_WEEKS', name='noticeperiod'), nullable=True),
    sa.Column('observations', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidato_email'), 'candidato', ['email'], unique=True)
    op.create_index(op.f('ix_candidato_full_name'), 'candidato', ['full_name'], unique=True)
    op.create_index(op.f('ix_candidato_linkedin_url'), 'candidato', ['linkedin_url'], unique=True)
    op.create_index(op.f('ix_candidato_phone'), 'candidato', ['phone'], unique=True)
    op.create_table('empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_company_name'), 'empresa', ['company_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'HEAD', 'SELECTOR', name='userrole'), nullable=False),
    sa.Column('vertical', sa.Enum('DEV', 'CLOUD_DEVOPS', 'DATA_AI', 'OPS', 'GENERAL', name='vertical'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_client_name'), 'cliente', ['client_name'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=300), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('ABIERTA', 'PAUSADA', 'CERRADA', name='estadojob'), nullable=True),
    sa.Column('type_of_process', sa.Enum('RENAISS_SIN_CLIENTE', 'RENAISS_CON_CLIENTE', 'STAFFED_CORTO', 'STAFFED_LARGO', name='tipoproceso'), nullable=True),
    sa.Column('vertical', sa.Enum('DEV', 'CLOUD_DEVOPS', 'DATA_AI', 'OPS', 'GENERAL', name='vertical'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_job_name'), 'job', ['job_name'], unique=True)
    op.create_table('proceso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('SOURCING', 'NO_COMIENZA', 'NO_CONTINUA', 'EN_PROCESO', name='estadogeneral'), nullable=True),
    sa.Column('substate_detail', sa.String(length=50), nullable=True),
    sa.Column('process_entry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('HR_interview', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proceso')
    op.drop_index(op.f('ix_job_job_name'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_cliente_client_name'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_table('user')
    op.drop_index(op.f('ix_empresa_company_name'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_index(op.f('ix_candidato_phone'), table_name='candidato')
    op.drop_index(op.f('ix_candidato_linkedin_url'), table_name='candidato')
    op.drop_index(op.f('ix_candidato_full_name'), table_name='candidato')
    op.drop_index(op.f('ix_candidato_email'), table_name='candidato')
    op.drop_table('candidato')
    # ### end Alembic commands ###
