from enum import Enum
class UserRole(str, Enum):
    ADMIN = "Admin"
    HEAD = "HEAD"
    SELECTOR = "Selector"
class TipoProceso(str, Enum):
    RENAISS_SIN_CLIENTE = "renaiss_sin_cliente"
    RENAISS_CON_CLIENTE = "renaiss_con_cliente"
    STAFFED_CORTO = "staffed_corto"
    STAFFED_LARGO = "staffed_largo"
class EstadoGeneral(str, Enum):
    SOURCING = "Sourcing"
    NO_COMIENZA = "No comienza"
    NO_CONTINUA = "No continua"
    EN_PROCESO = "En proceso"
class Fuente(str, Enum):
    HUNTING = "Hunting"
    APPLICATION = "Application"
    REFERAL = "Referal"
    INTERNSHIP = "Internship"
class ProvinciaArgentina(str, Enum):
    BUENOS_AIRES = "Buenos Aires"
    CATAMARCA = "Catamarca"
    CHACO = "Chaco"
    CHUBUT = "Chubut"
    CORDOBA = "Córdoba"
    CORRIENTES = "Corrientes"
    ENTRE_RIOS = "Entre Ríos"
    FORMOSA = "Formosa"
    JUJUY = "Jujuy"
    LA_PAMPA = "La Pampa"
    LA_RIOJA = "La Rioja"
    MENDOZA = "Mendoza"
    MISIONES = "Misiones"
    NEUQUEN = "Neuquén"
    RIO_NEGRO = "Río Negro"
    SALTA = "Salta"
    SAN_JUAN = "San Juan"
    SAN_LUIS = "San Luis"
    SANTA_CRUZ = "Santa Cruz"
    SANTA_FE = "Santa Fe"
    SANTIAGO_DEL_ESTERO = "Santiago del Estero"
    TIERRA_DEL_FUEGO = "Tierra del Fuego"
    TUCUMAN = "Tucumán"
class NoticePeriod(str, Enum):
    IMMEDIATE = "Immediate"
    ONE_WEEK = "1 week"
    TWO_WEEKS = "2 weeks"
    THREE_WEEKS = "3 weeks"
    FOUR_WEEKS = "4 weeks"
    MORE_THAN_FOUR_WEEKS = "More than 4 weeks"
class EstadoJob(str, Enum):
    ABIERTA = "ABIERTA"
    PAUSADA = "PAUSADA"
    CERRADA = "CERRADA"
    CANCELADA = "CANCELADA"
class Vertical(str, Enum):
    DEV = "Desarrollo"
    CLOUD_DEVOPS = "Cloud & DevOps"
    DATA_AI = "Data & AI"
    OPS = "Ops"
    GENERAL = "General"